#!/usr/bin/env node

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const bcrypt = require('bcrypt');
const { Pool } = require('pg');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

// Colors for console output
const colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    green: '\x1b[32m',
    red: '\x1b[31m',
    yellow: '\x1b[33m',
    blue: '\x1b[34m'
};

function log(message, color = 'reset') {
    console.log(`${colors[color]}${message}${colors.reset}`);
}

function prompt(question) {
    return new Promise(resolve => rl.question(question, resolve));
}

async function checkPrerequisites() {
    log('\n🔍 Checking prerequisites...\n', 'blue');
    
    try {
        // Check Node.js version
        const nodeVersion = execSync('node --version', { encoding: 'utf-8' }).trim();
        log(`✅ Node.js ${nodeVersion}`, 'green');
    } catch (e) {
        log('❌ Node.js not found', 'red');
        return false;
    }

    try {
        // Check Python version
        const pythonVersion = execSync('python3 --version 2>&1 || python --version', { encoding: 'utf-8' }).trim();
        log(`✅ Python ${pythonVersion}`, 'green');
    } catch (e) {
        log('⚠️  Python not found in PATH', 'yellow');
        log('   Install Python 3.9+ and try again', 'yellow');
        return false;
    }

    try {
        // Check PostgreSQL (try to connect)
        const testPool = new Pool({
            host: 'localhost',
            port: 5432,
            user: 'postgres',
            password: 'postgres',
            database: 'postgres'
        });
        await testPool.query('SELECT NOW()');
        await testPool.end();
        log(`✅ PostgreSQL (localhost:5432)`, 'green');
    } catch (e) {
        log('⚠️  PostgreSQL not accessible at localhost:5432', 'yellow');
        log('   Make sure PostgreSQL is running', 'yellow');
        // Don't return false, user might have custom setup
    }

    return true;
}

async function setupEnvironment() {
    log('\n⚙️  Setting up environment variables...\n', 'blue');

    const envPath = path.join(__dirname, '../../.env');
    
    if (fs.existsSync(envPath)) {
        const overwrite = await prompt('📄 .env already exists. Overwrite? (y/n): ');
        if (overwrite.toLowerCase() !== 'y') {
            log('✅ Keeping existing .env', 'green');
            return;
        }
    }

    const databaseUrl = await prompt('🗄️  Database URL (postgresql://user:password@host:port/db):\n   > ');
    const jwtSecret = await prompt('🔐 JWT Secret (or press Enter for auto-generate):\n   > ');
    const pythonPath = await prompt('🐍 Python path (default: ./venv/bin/python):\n   > ');
    const port = await prompt('🚀 Port (default: 3000):\n   > ');

    const env = `# Generated by setup script
PORT=${port || '3000'}
DATABASE_URL=${databaseUrl}
JWT_SECRET=${jwtSecret || generateJWTSecret()}
PYTHON_PATH=${pythonPath || './venv/bin/python'}
NODE_ENV=development
`;

    fs.writeFileSync(envPath, env);
    log('✅ .env file created', 'green');
}

async function setupDatabase(dbUrl) {
    log('\n💾 Setting up database...\n', 'blue');

    try {
        const pool = new Pool({
            connectionString: dbUrl
        });

        // Create users table
        await pool.query(`
            CREATE TABLE IF NOT EXISTS users (
                id SERIAL PRIMARY KEY,
                username VARCHAR(100) UNIQUE NOT NULL,
                email VARCHAR(255) NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                is_admin BOOLEAN DEFAULT FALSE,
                department_id INTEGER,
                created_at TIMESTAMP DEFAULT NOW()
            )
        `);
        log('✅ Users table created', 'green');

        // Create timetables table
        await pool.query(`
            CREATE TABLE IF NOT EXISTS timetables (
                id SERIAL PRIMARY KEY,
                user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
                name VARCHAR(255) NOT NULL,
                description TEXT,
                input_json JSONB NOT NULL,
                output_json JSONB,
                status VARCHAR(20) DEFAULT 'pending',
                error_message TEXT,
                created_at TIMESTAMP DEFAULT NOW(),
                updated_at TIMESTAMP DEFAULT NOW()
            )
        `);
        log('✅ Timetables table created', 'green');

        // Create audit_log table
        await pool.query(`
            CREATE TABLE IF NOT EXISTS audit_log (
                id SERIAL PRIMARY KEY,
                user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                target_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                actor_username TEXT,
                target_username TEXT,
                action VARCHAR(50) NOT NULL,
                old_data JSONB,
                new_data JSONB,
                created_at TIMESTAMP DEFAULT NOW()
            )
        `);
        log('✅ Audit log table created', 'green');

        // Check if admin exists
        const adminCheck = await pool.query('SELECT id FROM users WHERE is_admin = true LIMIT 1');
        
        if (adminCheck.rows.length === 0) {
            await createAdminUser(pool);
        } else {
            log('ℹ️  Admin user already exists', 'blue');
        }

        await pool.end();
        return true;
    } catch (err) {
        log(`❌ Database setup failed: ${err.message}`, 'red');
        return false;
    }
}

async function createAdminUser(pool) {
    log('\n👤 Creating admin account...\n', 'blue');

    const username = await prompt('Admin username: ');
    const email = await prompt('Admin email: ');
    const password = await prompt('Admin password: ');
    
    if (!username || !email || !password) {
        log('❌ All fields required', 'red');
        return false;
    }

    try {
        const hash = await bcrypt.hash(password, 10);
        const result = await pool.query(
            'INSERT INTO users (username, email, password_hash, is_admin) VALUES ($1, $2, $3, true) RETURNING id, username',
            [username, email, hash]
        );
        
        log(`✅ Admin user '${result.rows[0].username}' created`, 'green');
        return true;
    } catch (err) {
        log(`❌ Failed to create admin: ${err.message}`, 'red');
        return false;
    }
}

async function setupPythonVenv() {
    log('\n🐍 Setting up Python virtual environment...\n', 'blue');

    const venvPath = path.join(__dirname, '../../venv');
    
    if (fs.existsSync(venvPath)) {
        log('✅ Virtual environment already exists', 'green');
        return true;
    }

    try {
        log('Creating venv...', 'yellow');
        execSync('python3 -m venv venv', { cwd: path.join(__dirname, '../..'), stdio: 'inherit' });
        
        log('Installing OR-Tools...', 'yellow');
        const cmd = process.platform === 'win32' 
            ? 'venv\\Scripts\\pip install ortools'
            : './venv/bin/pip install ortools';
        
        execSync(cmd, { cwd: path.join(__dirname, '../..'), stdio: 'inherit' });
        log('✅ Python environment ready', 'green');
        return true;
    } catch (err) {
        log(`⚠️  Failed to setup Python venv: ${err.message}`, 'yellow');
        log('   Run manually: python3 -m venv venv && ./venv/bin/pip install ortools', 'yellow');
        return false;
    }
}

function generateJWTSecret() {
    return require('crypto').randomBytes(32).toString('hex');
}

async function main() {
    log('\n╔════════════════════════════════════════╗', 'blue');
    log('║  Timetable Scheduler - Setup Wizard    ║', 'blue');
    log('╚════════════════════════════════════════╝', 'blue');

    // Check prerequisites
    const prereqOk = await checkPrerequisites();
    if (!prereqOk) {
        log('\n⚠️  Some prerequisites are missing. Please install them and try again.', 'yellow');
        process.exit(1);
    }

    try {
        // Setup .env
        await setupEnvironment();

        // Read .env to get DATABASE_URL
        const envPath = path.join(__dirname, '../../.env');
        const envContent = fs.readFileSync(envPath, 'utf-8');
        const databaseUrlMatch = envContent.match(/DATABASE_URL=(.+)/);
        const dbUrl = databaseUrlMatch ? databaseUrlMatch[1].trim() : '';

        if (!dbUrl) {
            throw new Error('DATABASE_URL not found in .env');
        }

        // Setup database
        const dbOk = await setupDatabase(dbUrl);
        if (!dbOk) {
            log('\n⚠️  Database setup had issues. Please check your configuration.', 'yellow');
        }

        // Setup Python venv
        await setupPythonVenv();

        log('\n✅ Setup complete!' , 'green');
        log('\n📝 Next steps:', 'bright');
        log('   1. npm install', 'blue');
        log('   2. npm start', 'blue');
        log('\n🌐 Open http://localhost:3000 in your browser', 'green');
        log('', 'reset');

    } catch (err) {
        log(`\n❌ Setup failed: ${err.message}`, 'red');
        process.exit(1);
    } finally {
        rl.close();
    }
}

main();
